#define BAMBISA

namespace SwaggerParser
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.IO;
    using System.Linq;

    public class Program
    {
        public static void Main1(string[] args)
        {
            args = new[] {
                @"C:\Users\v-robmc\Desktop\New folder\auth.json",
                @"C:\Users\v-robmc\Desktop\New folder\code.cs",
            };

            var output = args.Last();
            var input = new string[args.Length - 1];
            for (int index = 0; index < input.Length; index++)
            {
                input[index] = args[index];
            }

            var definations = input.Select(file => SwaggerDefination2.FromNode(JsonConvert.DeserializeObject<JObject>(File.ReadAllText(file)))).ToArray();

            Debugger.Break();
        }

        private class CanAddResult
        {
            public bool Unique { get; set; }
            public string Existing { get; set; }
        }

        public static void Main(string[] args)
        {
            args = new[]
                {
                    @"C:\Users\v-robmc\Desktop\New folder\auth.json",
                    @"C:\Users\v-robmc\Desktop\New folder\calendar.json",
                    @"C:\Users\v-robmc\Desktop\New folder\group.json",
                    @"C:\Users\v-robmc\Desktop\New folder\message.json",
                    @"C:\Users\v-robmc\Desktop\New folder\feedback.json",
                    @"C:\Users\v-robmc\Desktop\New folder\Bambisa.cs",
                };

            var output = args.Last();
            var input = new string[args.Length - 1];
            for (int index = 0; index < input.Length; index++)
            {
                input[index] = args[index];
            }

            var definations = input.Select(file => ParseSwagger(File.ReadAllText(file))).ToList();
            var code = new CodersStringBuilder();
            var classes = new Dictionary<string, IEnumerable<SwaggerPropertry>>();
            var renderedClasses = new List<string>();
            code.AppendLine("// This file is autogenerated - any changes made to it maybe lost");
            code.AppendLine("namespace API");
            code.AppendLine("{");
            code.AppendLine("using System;");
            code.AppendLine("using System.Threading.Tasks;");
            code.AppendLine("using Newtonsoft.Json;");
#if BAMBISA
            code.AppendLine("using Universal;");
#endif
            code.AppendLine();
            foreach (var defination in definations)
            {
                foreach (var @class in defination.Classes)
                {
                    var canAddClass = CanAddClass(classes, new KeyValuePair<string, IEnumerable<SwaggerPropertry>>(@class.Name, @class.Properties));
                    if (canAddClass.Unique)
                    {
                        classes.Add(@class.Name, @class.Properties);
                    }
                    else
                    {
                        if (@class.Name.Equals(canAddClass.Existing))
                        {
                            continue;
                        }

                        foreach (var method in defination.Methods)
                        {
                            foreach (var parameter in method.Parameters.Where(_ => !_.CustomType && !string.IsNullOrWhiteSpace(_.Type) && _.Type.Equals(@class.Name)))
                            {
                                parameter.Type = canAddClass.Existing;
                            }

                            foreach (var response in method.Responses.Where(_ => !_.CustomType && !string.IsNullOrWhiteSpace(_.Type) && _.Type.Equals(@class.Name)))
                            {
                                response.Type = canAddClass.Existing;
                            }
                        }
                    }
                }

                var apiClassName = defination.Name.Replace(" ", "");
                code.AppendLine("/// <summary>");
                code.AppendLine("/// " + defination.Description);
                code.AppendLine("/// </summary>");
                if (defination.Warnings.Any())
                {
                    code.AppendLine("/// <remarks>");
                    code.AppendLine("/// The following issues were found in the swagger file");
                    foreach (var warning in defination.Warnings)
                    {
                        code.AppendLine("/// - " + warning);
                    }

                    code.AppendLine("/// </remarks>");
                }

                code.AppendLine("public class " + apiClassName);
                code.AppendLine("{");
                code.AppendLine("private readonly string baseUri;");
                code.AppendLine();
#if BAMBISA
                code.AppendLine("public " + apiClassName + "()");
                code.AppendLine("{");
                code.AppendLine("baseUri = Configuration.Get(ConfigKey.APIUrl)+\"" + defination.BasePath + "\";");
                code.AppendLine("}");
#else
                code.AppendLine("public " + apiClassName + "(string baseUri = \"" + defination.BaseUri.AbsoluteUri + "\")");
                code.AppendLine("{");
                code.AppendLine("    this.baseUri = baseUri;");
                code.AppendLine("}");
#endif

                foreach (var method in defination.Methods)
                {
                    var methodName = method.Path.IndexOf('/', 1) >= 0 ? method.Path.Substring(1, method.Path.IndexOf('/', 1) - 1) : method.Path.Substring(1);
                    code.AppendLine();
                    code.AppendLine("/// <summary>");
                    code.AppendLine("/// " + method.Description);
                    code.AppendLine("/// </summary>");

                    var parameters = "";

                    if (method.TokenAuth)
                    {
                        code.AppendLine("/// <param name=\"token\">The OAuth security token</param>");
                        parameters += "string token";
                    }

                    foreach (var parameter in method.Parameters)
                    {
                        code.AppendLine("/// <param name=\"" + parameter.Name + "\">" + parameter.Description + "</param>");
                        if (parameters.Length > 0)
                        {
                            parameters += ", ";
                        }

                        if (parameter.Type == null)
                        {
                            var @class = BuildClass(parameter.Name, parameter.Properties, methodName, "in");
                            var className = "";

                            var canAddClass = CanAddClass(classes, @class);
                            if (canAddClass.Unique)
                            {
                                classes.Add(@class.Key, @class.Value);
                                className = @class.Key;
                            }
                            else
                            {
                                className = canAddClass.Existing;
                            }

                            parameters += className + " " + parameter.Name;

                            var newClass = new SwaggerClass
                            {
                                Name = className,
                            };

                            newClass.Properties.AddRange(@class.Value);
                            defination.Classes.Add(newClass);
                        }
                        else
                        {
                            parameters += parameter.CustomType ? parameter.Type + " " + parameter.Name : ClassMapper(parameter.Type) + " " + parameter.Name;
                        }
                    }

                    var successResponse = method.Responses.First(_ => _.Code == 200);
                    var responseClass = "";
                    code.AppendLine("/// <returns>" + successResponse.Description + "</returns>");

                    var hasResponse = false;
                    var responseType = "";
                    var unwrappedClass = "object";

                    if (successResponse.Properties.Count == 0)
                    {
                        responseClass = "Task<WrappedResponse";
                        if (!string.IsNullOrWhiteSpace(successResponse.Type))
                        {
                            hasResponse = true;
                            responseType = successResponse.Type;
                            unwrappedClass = successResponse.Type;
                            responseClass += "<" + successResponse.Type;
                            if (successResponse.IsArray)
                            {
                                responseClass += "[]";
                                responseType += "[]";
                                unwrappedClass += "[]";
                            }

                            responseClass += ">>";
                        }
                        else
                        {
                            responseClass = "Task<WrappedResponse<object>>";
                        }
                    }
                    else
                    {
                        var @class = BuildClass("", successResponse.Properties, methodName, "out");
                        var className = "";

                        var canAddClass = CanAddClass(classes, @class);
                        if (canAddClass.Unique)
                        {
                            classes.Add(@class.Key, @class.Value);
                            className = @class.Key;
                        }
                        else
                        {
                            className = canAddClass.Existing;
                        }

                        unwrappedClass = className;

                        responseClass = "Task<WrappedResponse<" + className + ">>";
                        var newClass = new SwaggerClass
                        {
                            Name = className,
                        };

                        newClass.Properties.AddRange(@class.Value);
                        defination.Classes.Add(newClass);
                        responseType = className;
                        hasResponse = true;
                    }

                    var has500response = false;
                    var typeFor500 = "";

                    if (method.Responses.Any(_ => _.Code != 200))
                    {
                        var fivehundredresponse = method.Responses.FirstOrDefault(_ => _.Code == 500);
                        if (fivehundredresponse != null)
                        {
                            has500response = true;
                            typeFor500 = fivehundredresponse.Type;
                        }

                        code.AppendLine("/// <remarks>");
                        code.AppendLine("/// Other response codes");
                        foreach (var otherResponse in method.Responses.Where(_ => _.Code != 200).OrderBy(_ => _.Code))
                        {
                            code.Append("/// " + otherResponse.Code + ": " + otherResponse.Description);
                            if (!string.IsNullOrWhiteSpace(otherResponse.Type))
                            {
                                code.Append(" <seealso cref=\"" + otherResponse.Type + "\"/>", false);
                            }

                            code.AppendLine();
                        }

                        code.AppendLine("/// </remarks>");
                    }

                    code.AppendLine("public async " + responseClass + " " + method.HTTPAction + "_" + methodName + "(" + parameters + ")");
                    code.AppendLine("{");
                    code.AppendLine("var http = new HTTP();");
                    var actionLine = "";
                    if (hasResponse)
                    {
                        actionLine += "var response = ";
                    }

                    var methodPath = method.Path;
                    var pathParams = method.Parameters.Where(_ => _.Location.Equals("path", StringComparison.OrdinalIgnoreCase));
                    foreach (var pathParam in pathParams)
                    {
                        methodPath = methodPath.Replace("{" + pathParam.Name + "}", "\" + " + pathParam.Name + " + \"");
                    }

                    var queryParams = method.Parameters.Where(_ => _.Location.Equals("query", StringComparison.OrdinalIgnoreCase));
                    var firstQueryParam = true;
                    foreach (var queryParam in queryParams)
                    {
                        if (firstQueryParam)
                        {
                            firstQueryParam = false;
                            methodPath += "?";
                        }
                        else
                        {
                            methodPath += "&";
                        }

                        methodPath += queryParam.Name + "=\" + " + queryParam.Name + " + \"";
                    }

                    if (method.HTTPAction.Equals("post", StringComparison.OrdinalIgnoreCase))
                    {
                        var bodyParam = method.Parameters.FirstOrDefault(_ => _.Location.Equals("body", StringComparison.OrdinalIgnoreCase));
                        if (bodyParam != null)
                        {
                            code.AppendLine("var bodyJson = JsonConvert.SerializeObject(" + bodyParam.Name + ");");
                        }

                        actionLine += (hasResponse ? "await http.PostString" : "return await http.PostBool") + "(new Uri(baseUri + \"" + methodPath + "\", UriKind.Absolute)";

                        if (bodyParam != null)
                        {
                            actionLine += ", bodyJson";
                        }
                    }

                    if (method.HTTPAction.Equals("get", StringComparison.OrdinalIgnoreCase))
                    {
                        actionLine += "await http.GetString(new Uri(baseUri + \"" + methodPath + "\", UriKind.Absolute)";
                    }

                    if (method.HTTPAction.Equals("delete", StringComparison.OrdinalIgnoreCase))
                    {
                        actionLine += "await http.DeleteString(new Uri(baseUri + \"" + methodPath + "\", UriKind.Absolute)";
                    }

                    if (method.TokenAuth)
                    {
                        actionLine += ", token: token";
                    }

                    actionLine += ");";

                    actionLine = actionLine.Replace(" + \"\", UriKind.Absolute)", ", UriKind.Absolute)");

                    code.AppendLine(actionLine);

                    if (hasResponse)
                    {
                        code.AppendLine("if (response == null)");
                        code.AppendLine("{");
                        code.AppendLine("return new WrappedResponse<" + unwrappedClass + ">(false);");
                        code.AppendLine("}");
                        code.AppendLine();
                        if (has500response)
                        {
                            code.AppendLine("if (response.Succeeded)");
                            code.AppendLine("{");
                        }
                        code.AppendLine("try");
                        code.AppendLine("{");
                        code.AppendLine("var data = JsonConvert.DeserializeObject<" + responseType + ">(response.Data);");
                        code.AppendLine("return new WrappedResponse<" + unwrappedClass + ">(response.Succeeded, data);");
                        code.AppendLine("}");
                        code.AppendLine("catch (JsonReaderException)");
                        code.AppendLine("{");
                        code.AppendLine("return new WrappedResponse<" + unwrappedClass + ">(false);");
                        code.AppendLine("}");
                        if (has500response)
                        {
                            code.AppendLine("}");
                            code.AppendLine("else");
                            code.AppendLine("{");
                            code.AppendLine("try");
                            code.AppendLine("{");
                            code.AppendLine("var data = JsonConvert.DeserializeObject<" + typeFor500 + ">(response.Data);");
                            code.AppendLine("return new WrappedResponse<" + unwrappedClass + ">(data.message, data.error);");
                            code.AppendLine("}");
                            code.AppendLine("catch (JsonReaderException)");
                            code.AppendLine("{");
                            code.AppendLine("return new WrappedResponse<" + unwrappedClass + ">(false);");
                            code.AppendLine("}");
                            code.AppendLine("}");
                        }
                    }

                    code.AppendLine("}");
                }

                code.AppendLine("}");
                code.AppendLine();

                foreach (var @class in classes.OrderBy(_ => _.Key))
                {
                    var className = @class.Key.Replace(" ", "");
                    if (renderedClasses.Contains(className))
                    {
                        continue;
                    }

                    renderedClasses.Add(className);

                    code.AppendLine("public partial class " + className);
                    code.AppendLine("{");
                    foreach (var classProperty in @class.Value.OrderBy(_ => _.Name))
                    {
                        code.AppendLine("public " + ClassName(classProperty) + " " + classProperty.Name + " { get; set; }");
                        code.AppendLine();
                    }
                    code.AppendLine("}");
                    code.AppendLine();
                }
            }
            code.AppendLine("}");

            File.WriteAllText(output, code.ToString());
        }

        private static CanAddResult CanAddClass(Dictionary<string, IEnumerable<SwaggerPropertry>> classes, KeyValuePair<string, IEnumerable<SwaggerPropertry>> @class)
        {
            foreach (var existingClass in classes)
            {
                var same = true;
                foreach (var existingClassProperty in existingClass.Value)
                {
                    var newClassPropertyWithSameName = @class.Value.FirstOrDefault(_ => _.Name.Equals(existingClassProperty.Name));
                    if (newClassPropertyWithSameName == null)
                    {
                        same = false;
                        break;
                    }

                    if (existingClass.Value.Count() != @class.Value.Count())
                    {
                        same = false;
                        break;
                    }

                    if (!newClassPropertyWithSameName.Type.Equals(existingClassProperty.Type) ||
                        !newClassPropertyWithSameName.IsArray.Equals(existingClassProperty.IsArray) ||
                        !newClassPropertyWithSameName.CustomType.Equals(existingClassProperty.CustomType))
                    {
                        same = false;
                        break;
                    }
                }

                if (same)
                {
                    return new CanAddResult
                    {
                        Existing = existingClass.Key,
                        Unique = false
                    };
                }
            }

            return new CanAddResult
            {
                Existing = @class.Key,
                Unique = true
            };
        }

        private static KeyValuePair<string, IEnumerable<SwaggerPropertry>> BuildClass(string parameterName, IEnumerable<SwaggerPropertry> properties, string methodName, string direction)
        {
            var className = methodName + "_" + direction;
            if (!string.IsNullOrWhiteSpace(parameterName) && !parameterName.Equals("body", StringComparison.OrdinalIgnoreCase))
            {
                className += "_" + parameterName;
            }

            return new KeyValuePair<string, IEnumerable<SwaggerPropertry>>(className, properties);
        }

        private static string ClassMapper(string javascriptClass)
        {
            switch (javascriptClass.ToUpperInvariant())
            {
                case "STRING":
                    {
                        return "string";
                    }
                case "ARRAY":
                    {
                        return "";
                    }
                case "NUMBER":
                    {
                        return "double";
                    }
                case "BOOLEAN":
                    {
                        return "bool";
                    }
                default:
                    {
                        throw new Exception();
                    }
            }
        }

        private static string ClassName(SwaggerPropertry property)
        {
            var className = property.CustomType ? property.Type : ClassMapper(property.Type);
            if (property.IsArray)
            {
                className += "[]";
            }

            return className;
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="node"></param>
        /// <returns>
        /// </returns>
        private static IEnumerable<SwaggerPropertry> GetProperties(JToken node)
        {
            if (node == null)
            {
                return new List<SwaggerPropertry>(0);
            }

            var result = new List<SwaggerPropertry>();

            var properties = node.Children();
            foreach (var propertyParent in properties)
            {
                var property = propertyParent.First();

                var customType = false;
                var propertyType = "";
                if (property["type"] != null)
                {
                    propertyType = property["type"].Value<string>();
                }
                else
                {
                    if (property["$ref"] != null)
                    {
                        propertyType = property["$ref"].Value<string>().Substring(14);
                        customType = true;
                    }
                }

                var isArray = propertyType.Equals("array", StringComparison.OrdinalIgnoreCase);
                if (isArray)
                {
                    propertyType = property["items"]["$ref"].Value<string>().Substring(14);
                    customType = true;
                }

                if (string.IsNullOrWhiteSpace(propertyType))
                {
                    throw new Exception();
                }

                var swaggerProperty = new SwaggerPropertry
                {
                    Name = (propertyParent as JProperty).Name,
                    Type = propertyType,
                    Description = property["description"]?.Value<string>(),
                    IsArray = isArray,
                    CustomType = customType
                };

                result.Add(swaggerProperty);
            }

            return result;
        }

        private static SwaggerDefination ParseSwagger(string json)
        {
            var defination = new SwaggerDefination();
            var parsedJson = JsonConvert.DeserializeObject<JObject>(json);

            if (parsedJson["info"] != null)
            {
                defination.Name = parsedJson["info"]["title"].Value<string>();
                defination.Description = parsedJson["info"]["description"].Value<string>();
            }

            var url = "";
            if (parsedJson["schemes"] != null)
            {
                var schemes = parsedJson["schemes"].AsJEnumerable().Values<string>().ToArray();
                url = schemes.Length == 1 ? schemes.First() : schemes.Any(_ => _.Equals("https", StringComparison.OrdinalIgnoreCase)) ? "https" : schemes.First();
            }
            else
            {
                url = "http";
                defination.Warnings.Add("Missing scheme");
            }

            url += "://";
            url += parsedJson.Value<string>("host");
            url += parsedJson.Value<string>("basePath");
            defination.BaseUri = new Uri(url, UriKind.Absolute);
            defination.BasePath = parsedJson.Value<string>("basePath");

            if (parsedJson["definitions"] != null)
            {
                var classes = parsedJson["definitions"].AsJEnumerable();
                foreach (var classParent in classes)
                {
                    var @class = classParent.First();
                    var swaggerClass = new SwaggerClass
                    {
                        Name = (classParent as JProperty).Name,
                    };

                    swaggerClass.Properties.AddRange(GetProperties(@class["properties"]));

                    defination.Classes.Add(swaggerClass);
                }
            }

            var paths = parsedJson["paths"].AsJEnumerable();
            foreach (var path in paths)
            {
                var methods = path.First().Children();
                foreach (var methodParent in methods)
                {
                    var method = methodParent.First();

                    var swaggerMethod = new SwaggerMethod
                    {
                        Path = (path as JProperty).Name,
                        HTTPAction = (methodParent as JProperty).Name,
                        Description = method["description"].Value<string>()
                    };

                    if (method["security"] != null)
                    {
                        var securityMethods = method["security"].AsEnumerable();
                        foreach (var securityMethodParent in securityMethods)
                        {
                            var securityMethod = securityMethodParent.First();
                            var name = (securityMethod as JProperty).Name;
                            if (name.Equals("token", StringComparison.OrdinalIgnoreCase))
                            {
                                swaggerMethod.TokenAuth = true;
                            }
                        }
                    }

                    if (method["parameters"] != null)
                    {
                        var parameters = method["parameters"].AsJEnumerable();
                        foreach (var parameter in parameters)
                        {
                            var swaggerParameter = new SwaggerParameter
                            {
                                Description = parameter["description"]?.Value<string>(),
                                Location = parameter["in"].Value<string>(),
                                Name = parameter["name"].Value<string>(),
                                Required = parameter["required"].Value<bool>(),
                                Type = parameter["type"]?.Value<string>(),
                                CustomType = false
                            };

                            if (parameter["schema"] != null)
                            {
                                var schemaType = parameter["schema"]?["type"]?.Value<string>();
                                if (schemaType == null || schemaType.Equals("object", StringComparison.OrdinalIgnoreCase))
                                {
                                    var properties = parameter["schema"]["properties"];
                                    if (properties == null)
                                    {
                                        if (parameter["schema"]["$ref"] != null)
                                        {
                                            swaggerParameter.Type = parameter["schema"]["$ref"].Value<string>().Substring(14);
                                            swaggerParameter.CustomType = true;
                                        }
                                    }
                                    else
                                    {
                                        swaggerParameter.Properties.AddRange(GetProperties(properties));
                                    }
                                }
                                else
                                {
                                    swaggerParameter.Type = schemaType;
                                    swaggerParameter.Description += " - " + parameter["schema"]["description"].Value<string>();
                                }
                            }

                            swaggerMethod.Parameters.Add(swaggerParameter);
                        }
                    }

                    var responses = method["responses"].Children();
                    foreach (var responseParent in responses)
                    {
                        var response = responseParent.First();
                        var swaggerResponse = new SwaggerResponse
                        {
                            Code = Convert.ToInt32((responseParent as JProperty).Name),
                            Description = response["description"].Value<string>(),
                            IsArray = false,
                            Type = null,
                        };

                        if (response["schema"] != null)
                        {
                            var schemaType = response["schema"]["type"]?.Value<string>();
                            if (schemaType != null)
                            {
                                if (schemaType.Equals("object", StringComparison.OrdinalIgnoreCase))
                                {
                                    swaggerResponse.Properties.AddRange(GetProperties(response["schema"]["properties"]));
                                }

                                if (schemaType.Equals("array", StringComparison.OrdinalIgnoreCase))
                                {
                                    swaggerResponse.IsArray = true;
                                    swaggerResponse.Type = response["schema"]["items"]["$ref"].Value<string>().Substring(14);
                                }
                            }
                            else
                            {
                                var refType = response["schema"]["$ref"].Value<string>();
                                swaggerResponse.Type = refType.Substring(14);
                                swaggerResponse.CustomType = true;
                            }
                        }

                        swaggerMethod.Responses.Add(swaggerResponse);
                    }

                    defination.Methods.Add(swaggerMethod);
                }
            }

            return defination;
        }
    }

    internal class SwaggerClass
    {
        public string Name { get; set; }

        public List<SwaggerPropertry> Properties { get; } = new List<SwaggerPropertry>();
    }

    internal class SwaggerDefination
    {
        public string BasePath { get; internal set; }

        public Uri BaseUri { get; set; }

        public List<SwaggerClass> Classes { get; } = new List<SwaggerClass>();

        public string Description { get; internal set; }

        public List<SwaggerMethod> Methods { get; } = new List<SwaggerMethod>();

        public string Name { get; set; }

        public List<string> Warnings { get; } = new List<string>();
    }

    internal class SwaggerMethod
    {
        public string Description { get; set; }

        public string HTTPAction { get; set; }

        public List<SwaggerParameter> Parameters { get; } = new List<SwaggerParameter>();

        public string Path { get; set; }

        public List<SwaggerResponse> Responses { get; } = new List<SwaggerResponse>();

        public bool TokenAuth { get; set; }
    }

    internal class SwaggerParameter
    {
        public bool CustomType { get; internal set; }

        public string Description { get; set; }

        public string Location { get; set; }

        public string Name { get; set; }

        public List<SwaggerPropertry> Properties { get; } = new List<SwaggerPropertry>();

        public bool Required { get; set; }

        public string Type { get; internal set; }
    }

    internal class SwaggerPropertry
    {
        public bool CustomType { get; internal set; }

        public string Description { get; set; }

        public bool IsArray { get; internal set; }

        public string Name { get; set; }

        public string Type { get; set; }
    }

    internal class SwaggerResponse
    {
        public int Code { get; set; }
        public bool CustomType { get; internal set; }
        public string Description { get; set; }

        public bool IsArray { get; internal set; }

        public List<SwaggerPropertry> Properties { get; } = new List<SwaggerPropertry>();

        public string Type { get; internal set; }
    }
}