//nSwaggerVersion:0.0.4
// This file was automatically generated by nSwagger. Changes made to this file will be lost if nSwagger is run again. See https://github.com/rmaclean/nswagger for more information.
// This file was last generated at: 2016-03-15T14:15:19.4918281Z
namespace nSwagger {
    export module SwaggerPetstore {
        export interface Pet {
            id: number;
            name: string;
            tag: string;
        }

        export interface Error {
            code: number;
            message: string;
        }

        export interface API {
            setToken(value: string, headerOrQueryName: string, isQuery: boolean): void;
            getPets(): PromiseLike<Array<Pet>>;
        }
    }
}
