//nSwaggerVersion:0.0.3
// This file was automatically generated by nSwagger. Changes made to this file will be lost if nSwagger is run again. See https://github.com/rmaclean/nswagger for more information.
namespace nSwagger {
    export module SwaggerPetstore {
        export interface Pet {
        }

        export interface NewPet {
            name: string;
            tag: string;
        }

        export interface Error {
            code: number;
            message: string;
        }

        export interface findPetsRequest {
            tags?: Array<string>;
            limit?: number;
        }

        export interface addPetRequest {
            pet: NewPet;
        }

        export interface deletePetRequest {
            id: number;
        }

        export interface findpetbyidRequest {
            id: number;
        }

        export interface API {
            setToken(value: string, headerOrQueryName: string, isQuery: boolean): void;
            findPets(parameters?: findPetsRequest): PromiseLike<Array<Pet>>;
            addPet(parameters: addPetRequest): PromiseLike<Pet>;
            deletePet(parameters: deletePetRequest): PromiseLike<void>;
            findpetbyid(parameters: findpetbyidRequest): PromiseLike<Pet>;
        }
    }
}
