// This file was autogenerated by nSwagger 0.0.2 - changes made to it maybe lost if nSwagger is run again
namespace nSwagger {
    export module SwaggerPetstore {
        export interface Pet {
            id: number;
            name: string;
            tag: string;
        }

        export interface NewPet {
        }

        export interface ErrorModel {
            code: number;
            message: string;
        }

        export interface findPetsRequest {
            tags?: Array<string>;
            limit?: number;
        }

        export interface addPetRequest {
            pet: NewPet;
        }

        export interface deletePetRequest {
            id: number;
        }

        export interface findPetByIdRequest {
            id: number;
        }

        export interface API {
            setToken(value: string, headerOrQueryName: string, isQuery: boolean): void;
            findPets(parameters?: findPetsRequest): PromiseLike<Array<Pet>>;
            addPet(parameters: addPetRequest): PromiseLike<Pet>;
            deletePet(parameters: deletePetRequest): PromiseLike<void>;
            findPetById(parameters: findPetByIdRequest): PromiseLike<Pet>;
        }
    }
}
