// This file was autogenerated by nSwagger 0.0.1 - changes made to it maybe lost if nSwagger is run again
namespace nSwagger {
    export module SwaggerPetstore {
        export class Pet {
            id: number;
            name: string;
            tag: string;
        }

        export class PetInput {
        }

        export class ErrorModel {
            code: number;
            message: string;
        }

        export interface findPetsRequest {
            tags?: string[];
            limit?: number;
        }

        export interface addPetRequest {
            pet: PetInput;
        }

        export interface deletePetRequest {
            id: number;
        }

        export interface findPetByIdRequest {
            id: number;
        }

        export interface API {
            setToken(value: string, headerOrQueryName: string, isQuery: boolean): void;
            findPets(parameters?: findPetsRequest): PromiseLike<Pet>;
            addPet(parameters: addPetRequest): PromiseLike<Pet>;
            deletePet(parameters: deletePetRequest): PromiseLike<void>;
            findPetById(parameters: findPetByIdRequest): PromiseLike<Pet>;
        }
    }
}
