//nSwaggerVersion:0.0.4
// This file was automatically generated by nSwagger. Changes made to this file will be lost if nSwagger is run again. See https://github.com/rmaclean/nswagger for more information.
// This file was last generated at: 2016-03-15T14:15:16.9700174Z
namespace nSwagger {
    export module SwaggerPetstore {
        export interface Pet {
            id: number;
            name: string;
            tag: string;
        }

        export interface PetInput {
        }

        export interface ErrorModel {
            code: number;
            message: string;
        }

        export interface findPetsRequest {
            tags?: Array<string>;
            limit?: number;
        }

        export interface addPetRequest {
            pet: PetInput;
        }

        export interface deletePetRequest {
            id: number;
        }

        export interface findPetByIdRequest {
            id: number;
        }

        export interface API {
            setToken(value: string, headerOrQueryName: string, isQuery: boolean): void;
            findPets(parameters?: findPetsRequest): PromiseLike<Array<Pet>>;
            addPet(parameters: addPetRequest): PromiseLike<Pet>;
            deletePet(parameters: deletePetRequest): PromiseLike<void>;
            findPetById(parameters: findPetByIdRequest): PromiseLike<Pet>;
        }
    }
}
