//nSwaggerVersion:0.0.5
// This file was automatically generated by nSwagger. Changes made to this file will be lost if nSwagger is run again. See https://github.com/rmaclean/nswagger for more information.
// This file was last generated at: 2016-03-30T11:19:30.6876824Z
namespace nSwagger {
    export module SwaggerPetstore {
        export interface IPet {
            id: number;
            name: string;
            tag: string;
        }

        export interface IError {
            code: number;
            message: string;
        }

        export interface API {
            setToken(value: string, headerOrQueryName: string, isQuery: boolean): void;
            getPets(): PromiseLike<Array<IPet>>;
        }
    }
}
