//nSwaggerVersion:0.0.6
// This file was automatically generated by nSwagger. Changes made to this file will be lost if nSwagger is run again. See https://github.com/rmaclean/nswagger for more information.
// This file was last generated at: 2016-04-08T12:39:03.0167108Z
namespace nSwagger {
    export module SwaggerPetstore {
        export interface IPet {
            id: number;
            name: string;
            tag: string;
        }

        export interface INewPet {
        }

        export interface IErrorModel {
            code: number;
            message: string;
        }

        export interface IfindPetsRequest {
            tags?: Array<string>;
            limit?: number;
        }

        export interface IaddPetRequest {
            pet: INewPet;
        }

        export interface IdeletePetRequest {
            id: number;
        }

        export interface IfindPetByIdRequest {
            id: number;
        }

        export interface API {
            setToken(value: string, headerOrQueryName: string, isQuery: boolean): void;
            findPets(parameters?: IfindPetsRequest): PromiseLike<Array<IPet>>;
            addPet(parameters: IaddPetRequest): PromiseLike<IPet>;
            deletePet(parameters: IdeletePetRequest): PromiseLike<void>;
            findPetById(parameters: IfindPetByIdRequest): PromiseLike<IPet>;
        }
    }
}
